### ISSUE TITLE
deprecated float syntax

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/VPNkeyXchange#1]
per eMail von @magenbrot :

In der aktuellen Version von fastd muss "float" zwingend in eine eigene
Zeile: "float yes;" und ist nicht mehr Teil des remote-Parameters.

Auf dem fff-nue1 ist auch schon ein workaround hinterlegt, der genau
dafür sorgt:

```
filenames=$(cat /tmp/fastd_${project}.${hood}_output| grep ^#### | sed
-e 's/^####//' | sed -e 's/.conf//g')
for file in $filenames
do
grep -A100 ^####$file.conf$ /tmp/fastd_${project}.${hood}_output | grep
-v ^####$file.conf$ | grep -m1 ^### -B100 | grep -v ^### | sed 's/
float;/;/g' > /etc/fastd/$project.$hood/peers/$file
echo 'float yes;' >> /etc/fastd/$project.$hood/peers/$file
done
```

Gibts denn irgendwo noch ältere fastd-Versionen, die auf der alten
Syntax bestehen? Denn auch das rumänische GW zeigt deprecated Meldungen
im Syslog:

```
2014-05-26 12:20:03 +0200 --- Warning: peer `B0487ACB276E' uses
deprecated float syntax, please update your configuration
```

**Comment by adschm** [comment]
In der Firmware wird das ja abgefangen, außer betrifft es nur V1, daher mach ich das mal zu.
