### ISSUE TITLE
Fehlerhafte Links auf Hoodübersicht

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/VPNkeyXchange#18]
Auf der Seite
https://keyserver.freifunk-franken.de/v2/hoods.php?hoodfile=1
Sind die Links zu den Hoodfiles noch über die Koordinaten gelöst. Dies führt dazu wenn der Mittelpunkt einer voronoi Hood innerhalb einer Polyhood liegt auf die falsche Hood verwiesen wird (z.b. Hoodid 4 Hofheim)
Dies sollte man auf die ID anpassen

**Comment by adschm** [comment]
Oh ja, mach ich gelegentlich.

**Comment by adschm** [comment]
Fixed by: 0cfb406ee1f2ed657bdb60d4a558fcbc0d5e77ba
